x-overrides: &overrides
  user: root

services:
  bot:
    extends:
      file: compose.yml
      service: bot
    <<: *overrides

  celery-worker:
    extends:
      file: compose.yml
      service: celery-worker
    <<: *overrides
